services:
  odoo:
    image: odoo:16
    depends_on:
      - db
    restart: always
    ports:
      - "8069:8069"
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config:/etc/odoo
      - ./config/odoo.conf:/etc/odoo/odoo.conf
    env_file:
      - .env
  db:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - odoo-db-data:/var/lib/postgresql/data

volumes:
  odoo-web-data:
  odoo-db-data:
